// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgsrhjepzbeledmymyta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnc3JoamVwemJlbGVkbXlteXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNjI3NzUsImV4cCI6MjA4NjczODc3NX0.3-gq44mhhCzlZJXNqRAoIYfvTTAlxmzdD9_2YqPvNM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});